version: "3.8"

services:
  valkey-1:
    image: valkey/valkey:8.1.3
    command: [
      "valkey-server",
      "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "/data/nodes.conf",
      "--appendonly", "yes",
      "--cluster-announce-ip", "172.28.0.11",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379"
    ]
    volumes:
      - valkey-1-data:/data
    networks:
      valkey_net:
        ipv4_address: 172.28.0.11

  valkey-2:
    image: valkey/valkey:8.1.3
    command: [
      "valkey-server", "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "/data/nodes.conf",
      "--appendonly", "yes",
      "--cluster-announce-ip", "172.28.0.12",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379"
    ]
    volumes:
      - valkey-2-data:/data
    networks:
      valkey_net:
        ipv4_address: 172.28.0.12

  valkey-3:
    image: valkey/valkey:8.1.3
    command: [
      "valkey-server", "--port", "6379",
      "--cluster-enabled", "yes",
      "--cluster-config-file", "/data/nodes.conf",
      "--appendonly", "yes",
      "--cluster-announce-ip", "172.28.0.13",
      "--cluster-announce-port", "6379",
      "--cluster-announce-bus-port", "16379"
    ]
    volumes:
      - valkey-3-data:/data
    networks:
      valkey_net:
        ipv4_address: 172.28.0.13

  # One-off initializer to create the cluster (1 masters + 2 replicas)
  valkey-cluster:
    image: valkey/valkey:8.1.3
    depends_on:
      - valkey-1
      - valkey-2
      - valkey-3
    networks:
      - valkey_net
    entrypoint: ["/bin/sh","-c"]
    command: >-
      "sleep 3 && \
      valkey-cli --cluster create 172.28.0.11:6379 172.28.0.12:6379 172.28.0.13:6379 --cluster-replicas 0 --cluster-yes"

volumes:
  valkey-1-data:
  valkey-2-data:
  valkey-3-data:

networks:
  valkey_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
