version: "3.8"

services:

  valkey-cluster-creator:
    image: valkey/valkey:8.1.3
    volumes:
      - ./valkey/:/valkey/
    command: /bin/bash -c "/valkey/valkey_node.sh"
    ports:
      - "6381:6381"
      - "6382:6382"
      - "6383:6383"
